export const mock_categories = [
  {"id": 1, "name": "Jewelery", "parentCategoryId": 24},
  {"id": 2, "name": "Sports", "parentCategoryId": 24},
  {"id": 3, "name": "Baby", "parentCategoryId": 23},
  {"id": 4, "name": "Grocery", "parentCategoryId": 23},
  {"id": 5, "name": "Kids", "parentCategoryId": 23},
  {"id": 6, "name": "Health", "parentCategoryId": 23},
  {"id": 7, "name": "Outdoors", "parentCategoryId": 24},
  {"id": 8, "name": "Clothing", "parentCategoryId": 23},
  {"id": 9, "name": "Automotive", "parentCategoryId": 23},
  {"id": 10, "name": "Games", "parentCategoryId": 24},
  {"id": 11, "name": "Movies", "parentCategoryId": 24},
  {"id": 12, "name": "Computers", "parentCategoryId": 24},
  {"id": 13, "name": "Toys", "parentCategoryId": 24},
  {"id": 14, "name": "Books", "parentCategoryId": 23},
  {"id": 15, "name": "Home", "parentCategoryId": 23},
  {"id": 16, "name": "Industrial", "parentCategoryId": 23},
  {"id": 17, "name": "Beauty", "parentCategoryId": 24},
  {"id": 18, "name": "Music", "parentCategoryId": 24},
  {"id": 19, "name": "Electronics", "parentCategoryId": 24},
  {"id": 20, "name": "Shoes", "parentCategoryId": 23},
  {"id": 21, "name": "Garden", "parentCategoryId": 23},
  {"id": 22, "name": "Tools", "parentCategoryId": 23},
  {"id": 23, "name": "Necessary Expenses", "parentCategoryId": null},
  {"id": 24, "name": "Discretionary Expenses", "parentCategoryId": null}
];